### ISSUE TITLE
panic: Reuse of exported var name: utpAckSkippedResends

### ISSUE THREAD

**Issue by oliworx** [ipfs/ipget#31]
On Ubuntu 16.04 (64Bit) I installed from source as described in the README.
Whe executing ```ipget``` I get a runtime error:
```
$ ipget
2016/06/14 15:49:16 Reuse of exported var name: utpAckSkippedResends
panic: Reuse of exported var name: utpAckSkippedResends


goroutine 1 [running]:
panic(0xb2cb40, 0xc820077ee0)
	/home/oli/.linuxbrew/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
log.Panicln(0xc8200d1da8, 0x2, 0x2)
	/home/oli/.linuxbrew/Cellar/go/1.6.2/libexec/src/log/log.go:334 +0xc1
expvar.Publish(0xea12a0, 0x14, 0x7f1d18330cb0, 0xc820077e88)
	/home/oli/.linuxbrew/Cellar/go/1.6.2/libexec/src/expvar/expvar.go:254 +0x224
expvar.NewInt(0xea12a0, 0x14, 0xc)
	/home/oli/.linuxbrew/Cellar/go/1.6.2/libexec/src/expvar/expvar.go:272 +0x75
gx/ipfs/QmPSR1zYgWRmTSt6nTGXdeeUhWkq9AdvK4sva4Y2H5daPi/utp.init()
	/home/oli/.go/src/gx/ipfs/QmPSR1zYgWRmTSt6nTGXdeeUhWkq9AdvK4sva4Y2H5daPi/utp/expvar.go:6 +0xab
gx/ipfs/Qme5FbqN4BteaBcpbsj51fjzvqJhr54DigbqWAdXS5zgEe/go-libp2p-transport.init()
	/home/oli/.go/src/gx/ipfs/Qme5FbqN4BteaBcpbsj51fjzvqJhr54DigbqWAdXS5zgEe/go-libp2p-transport/utp.go:203 +0x4c
gx/ipfs/QmQkQP7WmeT9FRJDsEzAaGYDparttDiB6mCpVBrq2MuWQS/go-libp2p/p2p/net/conn.init()
	/home/oli/.go/src/gx/ipfs/QmQkQP7WmeT9FRJDsEzAaGYDparttDiB6mCpVBrq2MuWQS/go-libp2p/p2p/net/conn/secure_conn.go:124 +0x97
gx/ipfs/QmQkQP7WmeT9FRJDsEzAaGYDparttDiB6mCpVBrq2MuWQS/go-libp2p/p2p/net.init()
	/home/oli/.go/src/gx/ipfs/QmQkQP7WmeT9FRJDsEzAaGYDparttDiB6mCpVBrq2MuWQS/go-libp2p/p2p/net/interface.go:155 +0x45
gx/ipfs/QmQkQP7WmeT9FRJDsEzAaGYDparttDiB6mCpVBrq2MuWQS/go-libp2p/p2p/host.init()
	/home/oli/.go/src/gx/ipfs/QmQkQP7WmeT9FRJDsEzAaGYDparttDiB6mCpVBrq2MuWQS/go-libp2p/p2p/host/host.go:65 +0x51
github.com/ipfs/go-ipfs/core.init()
	/home/oli/.go/src/github.com/ipfs/go-ipfs/core/pathresolver.go:91 +0x6f
gx/ipfs/QmTrvhAM8734GYEY7JCtAgJrqUWkEvM7va9Qysq2u2o1LA/ipfs-embedded-shell.init()
	/home/oli/.go/src/gx/ipfs/QmTrvhAM8734GYEY7JCtAgJrqUWkEvM7va9Qysq2u2o1LA/ipfs-embedded-shell/shell.go:57 +0x5d
gx/ipfs/QmTgXW4YdmqzesTvAZzSBWawoc1MdBoXLtYM1VY1WkLUxg/fallback-ipfs-shell.init()
	/home/oli/.go/src/gx/ipfs/QmTgXW4YdmqzesTvAZzSBWawoc1MdBoXLtYM1VY1WkLUxg/fallback-ipfs-shell/shell.go:22 +0x59
main.init()
	/home/oli/.go/src/github.com/ipfs/ipget/ipget/main.go:60 +0x4f
```

**Comment by noffle** [comment]
Fixed on master. go-ipfs updated `go-multiaddr-net`, which caused ipget to rely on two different versions in its dependency tree. Thanks for noticing this! Let me know if you have any other problems. :)
